# This will be the first part of the title tag for your site 
# <title> {{site.name}} </title>
# ============================================================
name: "The Senior Software Engineer"
port: 5000
# Populates the meta description for the site. Should be under 150 characters for best SEO results.
# ============================================================
description: "The Senior Software Engineer by David Bryant Copeland is a 200 page guide to making the most out of your development career"

# Owner (organization or individual) of site content - You'll want to change this from mrmrs :)
# ============================================================
author: "davetron5000"

# Change this when you generate your site for production to your production URL i.e http://mrsjxn.com
# ============================================================
#url: "http://localhost:5000"
url: "http://theseniorsoftwareengineer.com"

# Publish future posts or not option. 
# ============================================================
future: true

# "A list of directories (including trailing slash) and files to exclude from the conversion"
# I normally exclude _sass, README*, and .gitignore
# Directories that start with an underscore _ are not copied over by default. Still like to include _sass anyways.
# ============================================================
exclude: [README.md, Rakefile]

# Pagination variable for how many posts to show in a list
# ============================================================
#paginate: 5

# Style of permalinks
# ============================================================
permalink: pretty

# Variable format options for URL styles below
# ============================================================
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-month:day-:year/:title.html/            => 04-29-2009/slap-chop.html
# /blog/:yearr/:month/:day/:title                 => /blog/2009/04/29/slap-chop/index.html

# Uncomment if you have pygments installed. Used for code syntax highlighting. 
# If you're not doing syntax highlighting you can delete this.
#pygments: true

# Custom
buy_link: http://transactions.sendowl.com/products/24086/D8D2ED13/add_to_cart



